name: Super Fun Happy Time Blog

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15

timezone: Asia/Jerusalem

# Details for the RSS feed generator
url:            'http://jek.assaflavie.com/'
author:         'Assaf Lavie'


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      excerpt_separator: "\n\n"
