name: Super Fun Happy Time Blog
description: 
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'http://jek.assaflavie.com/'
author:         'Assaf Lavie'
