name: Super Fun Happy Time Blog

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'http://jek.assaflavie.com/'
author:         'Assaf Lavie'
