name: Super Fun Happy Time Blog

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15

timezone: Asia/Jerusalem

# Details for the RSS feed generator
url:            'http://jek.assaflavie.com:4000'
author:         'Assaf Lavie'


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      excerpt_separator: "\n\n"

authors:
  assaf:
    name: Assaf Lavie
    display_name: Assaf Lavie
    gravatar: 6f27842fcf09e81f768a7ad354938468
    email: me@assaflavie.com
    web: http://assaflavie.com
    twitter: assaflavie
    github: assaflavie